### ISSUE TITLE
Question: Does it download originals only, or transformations too?

### ISSUE THREAD

**Issue by inspiredearth** [gavinkflam/cloudinarydump#1]
Hi there,
Thanks for sharing this script.
I wanted to know if it downloads all resources (original images, plus transformations), or just the original image resources?

Also, will it download all resources (*.*) or is it filtering for just images? (*.jpg, *.png)

Cheers,
Jonathan

**Comment by gavinkflam** [comment]
Hi Jonathan,

Glad that you find the script useful. :)

As I remember, the resources API list only the original images.
I worked on the script to escape from Cloudinary. Thus it was only used once.

Feel free to fork and bend the script to your will. Happy hacking!

Thanks,
Gavin

**Comment by inspiredearth** [comment]
Thanks Gavin. So, from what you understand, the API doesn't list non-images?

Also trying to escape from Cloudinary. Our costs have gone through the roof.

**Comment by gavinkflam** [comment]
You should need some extra API calls to list the derived images as well.
https://cloudinary.com/documentation/admin_api#details_of_a_single_resource

**Comment by gavinkflam** [comment]
I believe the interface is generic resources. Although I didn't host other resources on Cloudinary.
You can try the script / API so you will know the results.
https://cloudinary.com/documentation/admin_api#list_resources
